name: fittyus
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.2.1
  http: ^1.0.0
  shared_preferences: ^2.1.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.5
  pin_code_fields: ^8.0.1
  intl: ^0.18.1
  share_plus: ^7.1.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.0.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.10
  internet_connection_checker: ^1.0.0+1
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.5.1
  razorpay_flutter: ^1.3.5
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  file_picker: ^6.1.1
  paytm_allinonesdk: ^1.2.2
  uuid:
  youtube_player_flutter: ^8.1.2
  video_thumbnail: ^0.5.3
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.3
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  rxdart: ^0.27.7
  syncfusion_flutter_pdfviewer: ^24.1.43
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    # example:

  fonts:
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf

    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: Inter-ExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf

    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf

